interface Game {
  id: string,
  creatorId: string,
  courseName: string,
  layout: Layout,
  startDate: Date | null | undefined,
  endDate: Date,
  temperature: number | null,
  comment: string,
  scores: PlayerScores[],
  tags: Tag[],
  weatherConditions: Tag[],
  conditions: Tag[],
  highScorers: Player[],
  illegalScorers: Player[],
}
