interface Game {
  id: string,
  creatorId: string,
  courseName: string,
  layout: Layout,
  startDate: Date | undefined,
  endDate: Date,
  temperature: number | undefined,
  comments: GameComment[],
  scores: PlayerScores[],
  tags: Tag[],
  weatherConditions: Tag[],
  conditions: Tag[],
  highScorers: Player[],
  illegalScorers: Player[],
}
